### ISSUE TITLE
Delete code

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [BobliHH/Teme#2]
https://github.com/BobliHH/Teme/blob/f8edf296a44362fde0f97fecc354cea9deab4b23/Tema1/src/Dog.java#L15

Getterii si setterii sunt mosteniti. Aici trebuie definiti doar cei pentru 'color'

**Comment by BobliHH** [comment]
sters getterii si setterii care nu trebuiau, lasat doar pentru color.
